exports.getAddress = require("./get-address")
exports.cidToBytes = require("./cid-to-bytes")
exports.addCID = require("./deal-rewarder/add-cid")
exports.fund = require("./deal-rewarder/fund")
exports.claimBounty = require("./deal-rewarder/claim-bounty")
exports.makeDealProposal = require("./deal-client/make-deal-proposal")
exports.getDealProposal = require("./deal-client/get-deal-proposal")
exports.getDealStatus = require("./deal-client/get-deal-status")